spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-master:3306/oj_system?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      password: 123456
      lettuce:
        pool:
          max-active: 50
          max-idle: 5
          min-idle: 0
          max-wait: 5000
      database: 0
      cluster:
        nodes: redis01:6379,redis02:6379,redis03:6379,redis04:6379,redis05:6379,redis06:6379
      #host: 127.0.0.1
      connect-timeout: 5000
      timeout: 5000
mybatis:
  configuration: # 配置打印 MyBatis日志
    map-underscore-to-camel-case: true #配置驼峰自动转换
  # 配置 mybatis xml 的文件路径，在 resources/mapper 创建所有表的 xml 文件
  mapper-locations: classpath:mapper/**Mapper.xml
# 设置日志文件的文件名
logging:
  file:
    name: logger/spring-blog.log